spring:
  data:
    redis:
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
      port: 6379
      host: localhost
  thymeleaf:
    check-template-location: false
  datasource:
    url: jdbc:mysql://matprint.cykpr9exnjij.ap-northeast-2.rds.amazonaws.com:3306/matprint?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: jdk171717
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB
      location: /tmp/
    mvc:
      static-path-pattern: /static/**
  jackson:
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
  web:
    resources:
      static-locations: file:media/ ,classpath:/static
jwt:
  secret: aaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaesasdfqve