server:
  port: 8083
jwt:
  secret: ${JWT_SECRET}
cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: ${BUCKET}
    stack:
      auto: false
    credentials:
      secret-key: ${SECRET_KEY}
      access-key: ${ACCESS_KEY}
spring:
  data:
    redis:
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
      port: 6379
      host: localhost
  thymeleaf:
    check-template-location: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB
      location: /tmp/
  jackson:
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false