spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db?createDatabaseIfNotExist=true
    username: root
    password: asdf1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
      format_sql: true
    #show-sql: true
    #database-platform: org.hibernate.community.dialect.MySQL8Dialect
    #defer-datasource-initialization: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB
      location: /tmp/
    mvc:
      static-path-pattern: /static/**
    web:
      resources:
        static-locations: file:media/,classpath:/static
jwt:
  secret: aaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaesasdfqve